### ISSUE TITLE
Event Listeners 

### ISSUE THREAD

**Issue by kristinbaumann** [figma-plus/ui-plugin-boilerplate#1]
Hi,

first thanks for creating figma-plus and even providing a boilerplate for creating a plugin!
I played around with it, but unfortunately I couldn't get the event listeners working.

When I run the boilerplate plugin in the Figma desktop app, the buttons don't work (e.g. the primary button doesn't hide the UI). I noticed this error in the developer tools console in Figma:

![screenshot 2019-03-02 at 18 56 31](https://user-images.githubusercontent.com/14046209/53685621-66d39900-3d1d-11e9-9879-933056d48db7.png)

My guess is that the DOM nodes don't exist yet when calling `addEventListener`.

**Comment by cdes** [comment]
Hey @kristinbaumann!

Thank you for the kind words, and for reporting the issue.  I've pushed new changes and the issue is now resolved.

The problem is as you described, I just moved `this.attachEvents` to be inside the callback and everything worked.
